apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-deployment
  ports:
  - protocol: TCP
    targetPort: 80  # Port exposed by the container
    port: 8080  # Port exposed by the service
