# Default values for dummy-message-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: dummy-message-api

deployment:
  replicas: 1
  image:
    repository: magalhaesdit/dummy-message-api-public:latest
    # pull_secret: docker-hub-secret
    pullPolicy: Always
  containerPort: 8000

service:
  type: NodePort
  protocol: TCP
  port: 8000  # port exposed by the service
  targetPort: 8000  # port that the service will send requests to
  nodePort: 30100  # Usually between 30000-32767
